name: Code Quality

on:
  pull_request:
    branches:
      - main

jobs:
  lint-and-build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install dependencies
        run: npm install --legacy-peer-deps
        working-directory: ./quizeek

      - name: Run Lint
        run: npm run lint
        working-directory: ./quizeek

      - name: Run Build
        run: npm run build
        working-directory: ./quizeek
